name: tests

on:
  push:
    branches:
      - main
      - develop
      - correction
  pull_request:
    branches:
      - main
      - develop
      - correction

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 22

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}

      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
