name: tests

on:
  push:
    branches:
      - main
      - develop
      - correction
  pull_request:
    branches:
      - main
      - develop
      - correction

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le dépôt
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Xvfb (serveur d'affichage virtuel)
      - name: Set up Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x16 &

      # Étape 3 : Installer JDK 22
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 22

      # Étape 4 : Mise en cache des dépendances Maven
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}

      # Étape 5 : Vérifier la version de Java et Maven
      - name: Verify Java and Maven versions
        run: |
          java -version
          mvn -version

      # Étape 6 : Exécuter les tests Maven
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
