name: tests

on:
  push:
    branches:
      - main
      - develop
      - correction
  pull_request:
    branches:
      - main
      - develop
      - correction

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le dépôt
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Étape 2 : Installer JDK 22
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 22

      # Étape 3 : Mise en cache des dépendances Maven
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}

      # Étape 4 : Vérifier la version de Maven et Java
      - name: Verify Java and Maven versions
        run: |
          java -version
          mvn -version

      # Étape 5 : Exécuter les tests unitaires avec Maven
      - name: Run unit tests with Maven
        run: mvn -B test --file pom.xml

      # Étape 6 : Lancer les tests avec JUnit (classe spécifique TodoListApplicationTest)
      - name: Run tests with Maven (JUnit)
        run: |
          mvn clean test -Dtest=com.sio.javatd5sio2.TodoListApplicationTest

      # Étape 7 : Collecter les résultats des tests
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/test-classes  # ou le chemin des résultats de tests JUnit
